[package]
name = "rsip"
version = "0.1.0"
authors = ["Filippos Vasilakis <vasilakisfil@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "macros",
]

[dependencies]
uuid = { version = "0.8.1", features = ["v4"] }
md5 = "0.7.0"
bytes = "0.5.6"
log = "0.4.11"
base64 = "0.13.0"
nom = { version = "6.1.2", features = ["alloc", "regexp"] }
macros = { path = "./macros" }
