[package]
name = "macros"
version = "0.1.0"
authors = ["Filippos Vasilakis <vasilakisfil@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.65", features = ["extra-traits"] }
proc-macro2 = "1.0.27"
darling = "0.13.0"
